### ISSUE TITLE
Display Sql Query Time Error.

### ISSUE THREAD

**Issue by u2** [MiniProfiler/rack-mini-profiler#128]
```
/Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-mini-profiler-0.9.3/lib/mini_profiler/timer_struct/request.rb:85:in `new'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-mini-profiler-0.9.3/lib/mini_profiler/timer_struct/request.rb:85:in `add_sql'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-mini-profiler-0.9.3/lib/mini_profiler/profiling_methods.rb:8:in `record_sql'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-mini-profiler-0.9.3/lib/patches/sql_patches.rb:26:in `record_sql'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-mini-profiler-0.9.3/lib/patches/db/mysql2.rb:22:in `query'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `block in execute'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `execute'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/connection_adapters/mysql2_adapter.rb:228:in `execute'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/connection_adapters/mysql2_adapter.rb:232:in `exec_query'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/connection_adapters/mysql2_adapter.rb:240:in `select'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_all'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `block in select_all'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/query_cache.rb:83:in `cache_sql'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `select_all'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/querying.rb:39:in `find_by_sql'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/relation.rb:604:in `exec_queries'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/relation.rb:486:in `load'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/relation.rb:231:in `to_a'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/relation/finder_methods.rb:451:in `find_take'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/relation/finder_methods.rb:98:in `take'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/relation/finder_methods.rb:418:in `find_one'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/relation/finder_methods.rb:404:in `find_with_ids'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/relation/finder_methods.rb:68:in `find'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/querying.rb:3:in `find'
/Users/u2/weddingServer/app/controllers/application_controller.rb:44:in `current_user'
/Users/u2/weddingServer/app/controllers/application_controller.rb:22:in `user_for_paper_trail'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/paper_trail-3.0.6/lib/paper_trail/frameworks/rails/controller.rb:63:in `set_paper_trail_whodunnit'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:424:in `block in make_lambda'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:160:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:160:in `block in halting'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:166:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:166:in `block in halting'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:166:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:166:in `block in halting'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:86:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:86:in `run_callbacks'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/abstract_controller/callbacks.rb:19:in `process_action'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_controller/metal/rescue.rb:29:in `process_action'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/notifications.rb:159:in `block in instrument'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/notifications.rb:159:in `instrument'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/abstract_controller/base.rb:136:in `process'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionview-4.1.5/lib/action_view/rendering.rb:30:in `process'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_controller/metal.rb:196:in `dispatch'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_controller/metal.rb:232:in `block in action'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/routing/route_set.rb:50:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/journey/router.rb:71:in `block in call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/journey/router.rb:59:in `each'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/journey/router.rb:59:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/routing/route_set.rb:678:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/rack/agent_hooks.rb:26:in `traced_call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/rack/developer_mode.rb:56:in `traced_call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/meta_request-0.3.4/lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/meta_request-0.3.4/lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/remotipart-1.2.1/lib/remotipart/middleware.rb:27:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/flash.rb:254:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/query_cache.rb:36:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:82:in `run_callbacks'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/reloader.rb:73:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/better_errors-2.0.0/lib/better_errors/middleware.rb:84:in `protected_app_call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/better_errors-2.0.0/lib/better_errors/middleware.rb:79:in `better_errors_call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/better_errors-2.0.0/lib/better_errors/middleware.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-contrib-1.2.0/lib/rack/contrib/response_headers.rb:17:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/meta_request-0.3.4/lib/meta_request/middlewares/headers.rb:16:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/rack/logger.rb:38:in `call_app'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/rack/logger.rb:20:in `block in call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/tagged_logging.rb:26:in `tagged'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/tagged_logging.rb:68:in `tagged'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/rack/logger.rb:20:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/quiet_assets-1.0.3/lib/quiet_assets.rb:23:in `call_with_quiet_assets'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/static.rb:64:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/engine.rb:514:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/application.rb:144:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/railtie.rb:194:in `public_send'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/railtie.rb:194:in `method_missing'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-cors-0.2.9/lib/rack/cors.rb:54:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-mini-profiler-0.9.3/lib/mini_profiler/profiler.rb:276:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/faye-websocket-0.8.0/lib/faye/adapters/thin.rb:40:in `process'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/faye-websocket-0.8.0/lib/faye/adapters/thin.rb:44:in `receive_data'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/handler/thin.rb:16:in `run'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/server.rb:264:in `start'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/commands/server.rb:69:in `start'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:81:in `block in server'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:76:in `tap'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:76:in `server'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
/Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/commands.rb:17:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
SELECT  `users`.* FROM `users`  WHERE `users`.`id` = 6385 LIMIT 1   
```

**Comment by kbrock** [comment]
What is the exception that was occurring?
Is this still an issue?
