### ISSUE TITLE
nil value for X-MiniProfiler-Original-Cache-Control triggers error in rack/webbrick

### ISSUE THREAD

**Issue by kikonen** [MiniProfiler/rack-mini-profiler#322]
Encountering unexpected NPE with rack-mini-profiler 0.10.6

```
ERROR NoMethodError: undefined method `split' for nil:NilClass
	~/.rvm/gems/ruby-2.4.2@drt_ui/gems/rack-2.0.3/lib/rack/handler/webrick.rb:98:in `block in service'
	~/.rvm/gems/ruby-2.4.2@drt_ui/gems/rack-2.0.3/lib/rack/handler/webrick.rb:90:in `each'
	~/.rvm/gems/ruby-2.4.2@drt_ui/gems/rack-2.0.3/lib/rack/handler/webrick.rb:90:in `service'
	~/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
	~/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
	~/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'
```

Tracked down that offending header at that point is "X-MiniProfiler-Original-Cache-Control" which has value nil. Clearly nil value shouldn't exists as header value.

```
{
  "X-MiniProfiler-Original-Cache-Control" => nil,
   "Cache-Control" => "no-store, must-revalidate, private, max-age=0",
}
```

**Comment by kikonen** [comment]
Apparently fix is already included via https://github.com/MiniProfiler/rack-mini-profiler/pull/316

Possible to make new release with fix?

**Comment by SamSaffron** [comment]
Yes soonish!

**Comment by SamSaffron** [comment]
Just released a new version!
