### ISSUE TITLE
I'm using Mongoid but getting Gem Load Error is: uninitialized constant ActiveRecord::ConnectionAdapters

### ISSUE THREAD

**Issue by rgaufman** [MiniProfiler/rack-mini-profiler#349]
Hi there, I'm using rails (5.2.0), rack-mini-profiler (1.0.0) with mongoid (6.4.1) - I don't have (or want) ActiveRecord.

When I run rails c, I get this:

```
✗ rails c
Traceback (most recent call last):
	18: from bin/rails:4:in `<main>'
	17: from bin/rails:4:in `require'
	16: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<top (required)>'
	15: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/command.rb:46:in `invoke'
	14: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/command/base.rb:65:in `perform'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/console/console_command.rb:95:in `perform'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/command/actions.rb:17:in `require_application_and_environment!'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/command/actions.rb:17:in `require'
	 7: from /Users/hackeron/Dropbox/Development/Xanview/timeline/config/application.rb:26:in `<top (required)>'
	 6: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler.rb:114:in `require'
	 5: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/runtime.rb:65:in `require'
	 4: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/runtime.rb:65:in `each'
	 3: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/runtime.rb:76:in `block in require'
	 2: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/runtime.rb:76:in `each'
	 1: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/runtime.rb:80:in `block (2 levels) in require'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'rack-mini-profiler'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant ActiveRecord::ConnectionAdapters
Backtrace for gem load error is:
/usr/local/lib/ruby/gems/2.5.0/gems/rack-mini-profiler-1.0.0/lib/patches/db/activerecord.rb:47:in `insert_instrumentation'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-mini-profiler-1.0.0/lib/patches/db/activerecord.rb:53:in `<module:Rack>'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-mini-profiler-1.0.0/lib/patches/db/activerecord.rb:5:in `<top (required)>'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-mini-profiler-1.0.0/lib/patches/sql_patches.rb:61:in `block in patch'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-mini-profiler-1.0.0/lib/patches/sql_patches.rb:60:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-mini-profiler-1.0.0/lib/patches/sql_patches.rb:60:in `patch'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-mini-profiler-1.0.0/lib/patches/sql_patches.rb:66:in `<top (required)>'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-mini-profiler-1.0.0/lib/rack-mini-profiler.rb:31:in `<top (required)>'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/runtime.rb:81:in `require'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/runtime.rb:76:in `each'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/runtime.rb:76:in `block in require'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/runtime.rb:65:in `each'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/runtime.rb:65:in `require'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler.rb:114:in `require'
/Users/hackeron/Dropbox/Development/Xanview/timeline/config/application.rb:26:in `<top (required)>'
/usr/local/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/command/actions.rb:17:in `require'
/usr/local/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/command/actions.rb:17:in `require_application_and_environment!'
/usr/local/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/console/console_command.rb:95:in `perform'
/usr/local/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/usr/local/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/command/base.rb:65:in `perform'
/usr/local/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/command.rb:46:in `invoke'
/usr/local/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Bundler Error Backtrace:
```

Any ideas?

**Comment by gregmolnar** [comment]
@rgaufman Are you sure, you are not loading Active Record? In `config/application.rb` you shouldn't require `rails/all`, it should look something like this:
```
require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
require "active_job/railtie"
require "active_storage/engine"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
```
You should also remove all Active Record related configuration from the config files.

**Comment by rgaufman** [comment]
@gregmolnar yep, that's exactly what I have in application.rb - this issue seems to have surfaced after doing a bundle update to rails 5.2.0.

**Comment by gregmolnar** [comment]
That's odd, because the AR related parts of the profiler are only loaded if `ActiveRecord` is defined: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/lib/patches/sql_patches.rb#L36
Would you mind sharing your `Gemfile.lock`?

**Comment by mathyoudawson** [comment]
@rgaufman Did you find a resolution to this?

**Comment by rgaufman** [comment]
No, I disabled rack mini profiler :(

**Comment by nateberkopec** [comment]
[You can now disable patches.](https://github.com/MiniProfiler/rack-mini-profiler#patching-activerecord)
