### ISSUE TITLE
Fix broken Codecov integration

### ISSUE THREAD

**Issue by nateberkopec** [MiniProfiler/rack-mini-profiler#565]
Looks like @SamSaffron will have to fix this one.

[Build output.](https://github.com/MiniProfiler/rack-mini-profiler/actions/runs/4614880743/jobs/8158242306#step:6:36)

**Comment by olleolleolle** [comment]
In case that build output is eaten by log history reaping it:

<details>

```
Coverage report generated to /home/runner/work/rack-mini-profiler/rack-mini-profiler/coverage/codecov-result.json.
{"lib/mini_profiler/asset_version.rb"=>[nil, nil, 1, 1, 1, nil, nil], "lib/mini_profiler/client_settings.rb"=>[nil, nil, nil, 1, 1, 1, nil, 1, nil, 1, 1, 1, nil, 1, 1, nil, 1, 107, 107, 107, 107, 107, 107, nil, 107, nil, 107, 93, 58, 58, 58, nil, nil, nil...

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _\`|/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                               Ruby-0.6.0
==> GitHub Actions detected
x> No token specified or token is empty
==> Gzipping contents
==> Uploading reports
    url:   https://codecov.io/
    query: token=secret&flags&package=ruby-0.6.0&service=github-actions&branch=master&slug=MiniProfiler%2Frack-mini-profiler&build=4614880743&commit=2cd6fc68fc1ae314ca0cb0d71cdc4935b5b17b12
->  Pinging Codecov
https://codecov.io/upload/v4?token=secret&flags&package=ruby-0.6.0&service=github-actions&branch=master&slug=MiniProfiler%2Frack-mini-profiler&build=4614880743&commit=2cd6fc68fc1ae314ca0cb0d71cdc4935b5b17b12
{'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
/home/runner/work/rack-mini-profiler/rack-mini-profiler/vendor/bundle/ruby/3.2.0/gems/codecov-0.6.0/lib/codecov/uploader.rb:56:in `upload': Could not upload reports to Codecov (StandardError)
	from /home/runner/work/rack-mini-profiler/rack-mini-profiler/vendor/bundle/ruby/3.2.0/gems/codecov-0.6.0/lib/codecov.rb:15:in `format'
	from /home/runner/work/rack-mini-profiler/rack-mini-profiler/vendor/bundle/ruby/3.2.0/gems/simplecov-0.21.2/lib/simplecov/result.rb:51:in `format!'
	from /home/runner/work/rack-mini-profiler/rack-mini-profiler/vendor/bundle/ruby/3.2.0/gems/simplecov-0.21.2/lib/simplecov/configuration.rb:197:in `block in at_exit'
	from /home/runner/work/rack-mini-profiler/rack-mini-profiler/vendor/bundle/ruby/3.2.0/gems/simplecov-0.21.2/lib/simplecov.rb:189:in `run_exit_tasks!'
	from /home/runner/work/rack-mini-profiler/rack-mini-profiler/vendor/bundle/ruby/3.2.0/gems/simplecov-0.21.2/lib/simplecov.rb:179:in `at_exit_behavior'
	from /home/runner/work/rack-mini-profiler/rack-mini-profiler/vendor/bundle/ruby/3.2.0/gems/simplecov-0.21.2/lib/simplecov/defaults.rb:30:in `block in <top (required)>'
Error: Process completed with exit code 1.
```

</details>
